### ISSUE TITLE
Downloading the firmware.

### ISSUE THREAD

**Issue by drpioneer** [TheHWcave/OWON-XDM1041#1]
Hi!

Where can I download the firmware download utility for XDM1041?

**Comment by TheHWcave** [comment]
I don't know. I was hoping it has been used by OWON for other meters/scopes...  (I don't think its XDM1041 specific) and be accessible somewhere. I have got a version from Owon but its filesize is really big and Github won't led me upload it.  I am trying to do it in chunks but I have to go on a business trip and won't be able to work on it for a while

    On Friday, 19 November 2021, 06:07:01 GMT, drpioneer ***@***.***> wrote:  
 
 


Hi!

Where can I download the firmware download utility for XDM1041?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by drpioneer** [comment]
According to the instructions: https://github.com/TheHWcave/OWON-XDM1041/blob/main/OWON%20firmware/Readme.txt successfully updated my multimeter. 
Thanks.
