### ISSUE TITLE
For the script to work with Ubuntu 22.04, remove brltty

### ISSUE THREAD

**Issue by jaap59** [TheHWcave/OWON-XDM1041#6]
In order to use the serial connection with the Owon Digital Multimeter you will have to remove "brltty" from Ubuntu 22.04.

"sudo apt remove brltty"

Apparently this program prevents the use of the CH340 serial driver in general (nothing to do with the script).

Tested and working fine now. Thanks for the script!

**Comment by TheHWcave** [comment]
Wow that Britty (Braille reader) is really badly designed, breaking all the other stuff. Thanks for the info. 

    On Monday, 5 June 2023 at 14:18:25 BST, jaap59 ***@***.***> wrote:  
 
 


In order to use the serial connection with the Owon Digital Multimeter you will have to remove "brltty" from Ubuntu 22.04.

"sudo apt remove brltty"

Apparently this program prevents the use of the CH340 serial driver in general (nothing to do with the script).

Tested and working fine now. Thanks for the script!

**Comment by jaap59** [comment]
Issue closed now the work around is known.
